pipeline {
    agent any

    environment {
        MAVEN_HOME = tool 'Maven 3.9.6'
    }

    stages {
        stage('Clone') {
            steps {
                git 'https://github.com/BALRAJ1313/ecommerce-services.git'
            }
        }

        stage('Build') {
            steps {
                dir('order-service') {
                    sh "${MAVEN_HOME}/bin/mvn clean package -DskipTests"
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('order-service') {
                    script {
                        dockerImage = docker.build("order-service:latest")
                    }
                }
            }
        }

        stage('Run Container') {
            steps {
                script {
                    sh 'docker stop order-service || true && docker rm order-service || true'
                    sh 'docker run -d --name order-service -p 8081:8080 order-service:latest'
                }
            }
        }
    }
}
